### ISSUE TITLE
Soda having small lag spikes on a simple project

### ISSUE THREAD

**Issue by ghost** [JoeStrout/soda#12]
When running the `server_in_smoke.ms` example project (after replacing `soda.exe` with the appropriate OS-specific version), the game frequently spikes below 30 FPS (especially when updating multiple sprites at once), but otherwise has a stable 60 fps. Is anyone else experiencing this issue? If so, why might this be happening with such a relatively small project? (comment line 11 to see the lag when creating new sprites on a smaller project)

Tested on the lastest soda build, on windows 10.

[soda fps lag.zip](https://github.com/user-attachments/files/17910012/soda.fps.lag.zip)

![image](https://github.com/user-attachments/assets/74cf5585-4176-430f-8edf-6cc070fca3f4)
![image](https://github.com/user-attachments/assets/e41481f1-aefa-44c8-b951-3b3fa76244fd)

**Comment by JoeStrout** [comment]
Are you sure that project is complete?  I seem to be missing spriteFont.ms (which windowManager.ms is trying to import).

**Comment by JoeStrout** [comment]
...I did try commenting out line 11, which eliminated the errors, but no matter how furiously I click to create puffs of smoke(?), my "Lagspikes Total:" is still 0.

<img width="1192" alt="image" src="https://github.com/user-attachments/assets/a8d28ff7-a551-423e-8418-9f93fc6a0be5">

**Comment by ghost** [comment]
Ah, sorry. Must just be my pc playing up again xd
