### ISSUE TITLE
Sprite bounds are always square

### ISSUE THREAD

**Issue by ghost** [JoeStrout/soda#13]
When attempting to detect collisions using sprite bounds (e.g. Sprite.contains(x, y) and Sprite.overlaps(Sprite2)), the bounds behave as if they are square, even when the height is correctly configured.

You can observe this by downloading the test project: hover above or below the sprite, and it will turn gray. The second sprite also turns red when it overlaps the first. This happens despite the sprite bounds' width and height being explicitly set, and the image itself having dimensions of 64x16.

[brokenBounds.zip](https://github.com/user-attachments/files/17926757/brokenBounds.zip)

**Comment by JoeStrout** [comment]
Well spotted!  Fix pushed.
